Repository cozy/cozy-home, pull requests merged in 2018-10, with the labels that each got.

#963 Ignore empty password
  src/components/AccountLoginForm.jsx
  src/lib/accounts.js
  test/lib/__snapshots__/accounts.spec.js.snap
  test/lib/accounts.spec.js
Labels: bug

#964 Realtime for triggers
  src/ducks/connections/index.js
  src/ducks/triggers/index.js
  src/lib/CollectStore.js
  src/lib/triggers.js
Labels: bug, enhancement

#966 Avoid empty Login
  src/lib/accounts.js
  test/lib/__snapshots__/accounts.spec.js.snap
Labels: bug

#960 Update configuration documentation
  docs/configuration.md
  src/config/collect.json
Labels: enhancement

#961 feat: New home layout
  src/assets/icons/broken.svg
  src/assets/icons/icon-plus-add-service.svg
  src/components/AddServiceTile.jsx
  src/components/AppTile.jsx
  src/components/Applications.jsx
  src/components/Home.jsx
  src/components/KonnectorTile.jsx
  src/components/Services.jsx
  src/components/helpers/fillWithGhostItems.jsx
  src/lib/konnectors.js
  src/styles/app.styl
  src/styles/error.styl
  src/styles/lists.styl
Labels: enhancement

#967 fix: 🎨 UI Enhancements for Home
  src/styles/lists.styl
Labels: enhancement

#968 fix: 🎨 Increase konnector tile hover effect
  src/styles/lists.styl
Labels: enhancement

#969 fix: 🐛 Home UI fixes
  src/styles/lists.styl
  src/targets/browser/index.jsx
Labels: bug

#970 fix: 🎨 missing border radius on app item
  src/styles/lists.styl
Labels: bug

#972 feat: update locales + add notification circle
  src/locales/en.json
  src/styles/lists.styl
  test/components/__snapshots__/Loading.test.js.snap
Labels: enhancement

#987 Filter hidden apps
  src/components/Applications.jsx
  src/lib/tutorial.js
Labels: enhancement

#988 Hide konnector errors if flag is present in features
  package.json
  src/components/KonnectorTile.jsx
  src/containers/App.jsx
  yarn.lock
Labels: enhancement

#990 Linting
  .eslintrc.json
  package.json
  src/components/AccountConnectionData.jsx
  src/components/AccountLoginForm.jsx
  src/components/AccountPicker.jsx
  src/components/AddServiceTile.jsx
  src/components/Applications.jsx
  src/components/CozyContext.jsx
  src/components/DataItem.jsx
  src/components/DescriptionContent.jsx
  src/components/Field.jsx
  src/components/Home.jsx
  src/components/IntentRedirect.jsx
  src/components/KonnectorEdit.jsx
  src/components/KonnectorFolder.jsx
  src/components/KonnectorSync.jsx
  src/components/KonnectorTile.jsx
  src/components/Notifier.jsx
  src/components/ReactMarkdownWrapper.jsx
  src/components/Services.jsx
  src/components/appEntryPoint.jsx
  src/components/services/CreateAccountService.jsx
  src/components/services/ServiceKonnector.jsx
  src/containers/AccountConnection.jsx
  src/containers/App.jsx
  src/containers/ConnectionManagement.jsx
  src/containers/IntentService.jsx
  src/ducks/connections/components/queue/index.jsx
  src/ducks/connections/components/queue/queue.jsx
  src/ducks/connections/index.js
  src/ducks/context/index.js
  src/lib/CollectStore.js
  src/lib/icons.js
  src/lib/middlewares/konnectorsI18n.js
  src/lib/realtime.js
  src/lib/redux-cozy-client/CozyClient.js
  src/lib/redux-cozy-client/DataAccessFacade.js
  src/lib/redux-cozy-client/adapters/CozyStackAdapter.js
  src/lib/redux-cozy-client/adapters/PouchdbAdapter.js
  src/lib/redux-cozy-client/authentication/mobile.js
  src/lib/redux-cozy-client/middleware.js
  src/lib/redux-cozy-client/reducer.js
  src/lib/redux-cozy-client/slices/sharings.js
  src/lib/redux-cozy-client/slices/synchronization.js
  src/lib/statefulComponent.jsx
  src/lib/statefulForm.jsx
  src/lib/tutorial.js
  test/components/DescriptionContent.spec.js
  test/components/__snapshots__/ReactMarkdownWrapper.test.js.snap
  test/lib/accounts.spec.js
  yarn.lock
Labels: enhancement

#995 fix: 🐛 Fixed Spinner size so it doesn't jump
  src/components/AddServiceTile.jsx
Labels: bug
